apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: rpunct
spec:
  name: rpunct
  predictors:
  - annotations:
      seldon.io/no-engine: "true"
      sidecar.istio.io/proxyCPULimit: "300m"
      sidecar.istio.io/proxyMemoryLimit: "300Mi"
    componentSpecs:
    - spec:
        terminationGracePeriodSeconds: 60
        containers:
        - name: rpunct
          image: localhost:5001/rpunct:latest
          imagePullPolicy: Always
          env:
            - name: SELDON_LOG_LEVEL
              value: 'WARNING'
            - name: SELDON_DEBUG
              value: 'true'
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
              cpu: 1000m
              memory: 1000Mi
    graph:
      children: []
      endpoint:
        type: REST
      name: rpunct
      type: MODEL
    name: rpunct
    replicas: 1
