apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: sentiment
spec:
  name: sentiment
  predictors:
  - annotations:
      seldon.io/no-engine: "true"
      sidecar.istio.io/proxyCPULimit: "300m"
      sidecar.istio.io/proxyMemoryLimit: "300Mi"
    componentSpecs:
    - spec:
        terminationGracePeriodSeconds: 60
        containers:
        - name: sentiment
          image: localhost:5001/sentiment:latest
          imagePullPolicy: Always
          env:
            - name: SELDON_LOG_LEVEL
              value: 'WARNING'
            - name: SELDON_DEBUG
              value: 'false'
            - name: GRPC_WORKERS
              value: '0'
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
              cpu: 1000m
              memory: 1000Mi
    graph:
      children: []
      endpoint:
        type: REST
      name: sentiment
      type: MODEL
    name: sentiment
    replicas: 1
